name: Bug Report
description: File a clear and concise bug report
labels: ["bug", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        ## Before you start
        1. **Make sure you are on the latest version.**
        2. If you encountered the issue after you installed, updated, or reloaded, **please try restarting before reporting the bug.**

  - type: checkboxes
    id: no_duplicate_issues
    attributes:
      label: "Please check that this issue hasn't been reported before."
      description: "Use the **Label filters** to help make your search more focused."
      options:
        - label: "I searched previous [Bug Reports](https://github.com/reworkd/AgentGPT/labels/bug) and didn't find any similar reports."
          required: true

  - type: textarea
    id: expected_behavior
    attributes:
      label: Expected Behavior
      description: "Describe what **should** happen."
      validations:
        required: true

  - type: textarea
    id: current_behavior
    attributes:
      label: Current Behavior
      description: |
        Describe what happens instead of the expected behavior.
        Including screenshots is encouraged.
      validations:
        required: true

  - type: textarea
    id: reproduce_steps
    attributes:
      label: Steps to Reproduce
      description: |
        Provide detailed steps a developer can take to reproduce the issue.
        The more detail you provide, the easier it will be to narrow down and fix the bug.
        Paste in tasks and/or queries **as text, not screenshots.**
      validations:
        required: true

  - type: textarea
    id: possible_solution
    attributes:
      label: Possible Solution
      description: |
        Not obligatory, but please suggest a fix or reason for the bug, if you have an idea.

  - type: checkboxes
    id: operating_systems
    attributes:
      label: Which Operating Systems are you using?
      description: You may select more than one.
      options:
        - label: Android
        - label: iPhone/iPad
        - label: Linux
        - label: macOS
        - label: Windows

  - type: checkboxes
    id: acknowledgements
    attributes:
      label: 'Acknowledgements'
      description: 'Please confirm the following:'
      options:
        - label: 'My issue title is concise, descriptive, and in title casing.'
          required: true
        - label: 'I have searched the existing issues to make sure this bug has not been reported yet.'
          required: true
        - label: 'I am using the latest version of AgentGPT.'
          required: true
        - label: 'I have provided enough information for the maintainers to reproduce and diagnose the issue.'
          required: true
