blank_issues_enabled: true

contact_links:
  - name: Ask a question  # Ask questions and discuss with other community members
    url: https://github.com/reworkd/AgentGPT/discussions/categories/q-a

  - name: Discuss the Project in Discord  # Join the project's Discord server to discuss and collaborate
    url: https://discord.gg/jjYCfaqu
