name: Documentation Improvement Suggestion
description: Suggest an improvement to the project documentation.
labels: ['documentation', 'triage']
body:
  - type: markdown
    attributes:
      value: '## :books: Documentation Improvement Suggestion :books:'
  - type: markdown
    attributes:
      value: |
        * Ask questions in [Discord](https://discord.gg/jjYCfaqu).
        * Before you file an issue, please read the [Contributing guide](https://github.com/reworkd/AgentGPT/tree/main/.github/CONTRIBUTING.md).
        * Make sure someone hasn't already opened a [similar issue](https://github.com/reworkd/AgentGPT/issues).
  - type: textarea
    attributes:
      label: Affected Documentation
      description: Please link to the article you'd like to see updated.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposed Changes
      description: |
        - Describe the changes you'd like to see in detail.
        - Explain why the docs should be changed and which use cases it supports.
        - Describe the expected outcome.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional Information
      description: Add any other context, screenshots, or references about the feature request here.
    validations:
      required: false
  - type: checkboxes
    id: acknowledgements
    attributes:
      label: 'Acknowledgements'
      description: 'Please confirm the following:'
      options:
        - label: 'I have made sure my issue title is concise, descriptive, and in title casing.'
          required: true
        - label: 'I have searched the existing issues to ensure this feature request has not been made yet.'
          required: true
        - label: 'I have provided enough information for the maintainers to understand and evaluate this request.'
          required: true

